### ISSUE TITLE
Dashboard untuk Mengelola Link Pengguna

### ISSUE THREAD

**Issue by antheiz** [antheiz/kastau-link#10]
Buat halaman dashboard agar pengguna yang memiliki akun dapat mengelola tautan dengan mudah.

- [ ] **Desain & Implementasi:** Buat tampilan dan fungsi dasar halaman dashboard untuk mengelola tautan.
- [ ] **Otentikasi:** Pastikan hanya pengguna masuk yang dapat mengakses halaman dashboard.
- [ ] **Dokumentasi:** Tulis panduan pengguna untuk menggunakan halaman dashboard.

**Comment by karokari** [comment]
> Buat halaman dashboard agar pengguna yang memiliki akun dapat mengelola tautan dengan mudah.
> 
> * [ ]  **Desain & Implementasi:** Buat tampilan dan fungsi dasar halaman dashboard untuk mengelola tautan.
> * [ ]  **Otentikasi:** Pastikan hanya pengguna masuk yang dapat mengakses halaman dashboard.
> * [ ]  **Dokumentasi:** Tulis panduan pengguna untuk menggunakan halaman dashboard.

Hi, saya tertarik untuk berkontribusi untuk masalah ini. Saya ingin menangani pembuatan halaman dashboard.
Apakah saya bisa diberikan akses atau ditugaskan untuk pekerjaan ini? 

Apakah Anda bisa men-assign tugas ini kepada saya? Saya akan segera mulai bekerja pada halaman dashboard.

Terima kasih!

**Comment by antheiz** [comment]
> > Buat halaman dashboard agar pengguna yang memiliki akun dapat mengelola tautan dengan mudah.
> > 
> > * [ ]   **Desain & Implementasi:** Buat tampilan dan fungsi dasar halaman dashboard untuk mengelola tautan.
> > * [ ]   **Otentikasi:** Pastikan hanya pengguna masuk yang dapat mengakses halaman dashboard.
> > * [ ]   **Dokumentasi:** Tulis panduan pengguna untuk menggunakan halaman dashboard.
> 
> Hi, saya tertarik untuk berkontribusi untuk masalah ini. Saya ingin menangani pembuatan halaman dashboard. Apakah saya bisa diberikan akses atau ditugaskan untuk pekerjaan ini?
> 
> Apakah Anda bisa men-assign tugas ini kepada saya? Saya akan segera mulai bekerja pada halaman dashboard.
> 
> Terima kasih!

Terima kasih atas minat Anda untuk berkontribusi ke proyek kami! Saya telah men-assign tugas pembuatan halaman dashboard kepada Anda. Silakan mulai bekerja, dan jika Anda memiliki pertanyaan atau memerlukan bantuan, jangan ragu untuk bertanya di komentar ini.
